# Generated by Django 3.0.3 on 2020-04-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('articuloid', models.IntegerField(db_column='ArticuloID', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=30)),
            ],
            options={
                'db_table': 'Articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestid', models.IntegerField(db_column='RequestID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
            ],
            options={
                'db_table': 'Request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requisiciones',
            fields=[
                ('requestid', models.IntegerField(db_column='RequestID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('nombrereq', models.CharField(db_column='NombreReq', max_length=30)),
            ],
            options={
                'db_table': 'Requisiciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requisicionarticulo',
            fields=[
                ('requestid', models.OneToOneField(db_column='RequestID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Inventarios.Requisiciones')),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
            ],
            options={
                'db_table': 'RequisicionArticulo',
                'managed': False,
            },
        ),
    ]
