# Generated by Django 3.0.3 on 2020-04-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AlterModelTable(
            name='articulos',
            table='ListaArticulos',
        ),
        migrations.DeleteModel(
            name='Requisicionarticulo',
        ),
        migrations.DeleteModel(
            name='Requisiciones',
        ),
    ]
