# Generated by Django 3.0.3 on 2020-04-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0002_auto_20200406_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisiciones',
            fields=[
                ('requestid', models.IntegerField(db_column='RequestId', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='FechaReq')),
                ('nombre', models.CharField(db_column='NombreReq,', max_length=30)),
            ],
            options={
                'db_table': 'ListaRequests',
                'managed': False,
            },
        ),
    ]
