# Generated by Django 3.0.3 on 2020-04-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0003_requisiciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestArticulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
            ],
            options={
                'db_table': 'RequestArticulos',
                'managed': False,
            },
        ),
    ]
