# Generated by Django 3.0.3 on 2020-04-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0004_requestarticulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentDrug',
            fields=[
                ('MedCode', models.IntegerField(db_column='MedCode', primary_key=True, serialize=False)),
                ('MedDescription', models.CharField(db_column='MedDescription', max_length=100)),
                ('MedPharmacon', models.CharField(db_column='MedPharmacon', max_length=50)),
                ('MedFamily', models.CharField(db_column='MedFamily', max_length=80)),
            ],
            options={
                'db_table': 'PatentDrug',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='POReqMedCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmountRequested', models.IntegerField(db_column='AmountRequested')),
            ],
            options={
                'db_table': 'POReqMedCode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('PurchaseNumber', models.IntegerField(db_column='PurchaseNumber', primary_key=True, serialize=False)),
                ('OrderDate', models.DateField(db_column='OrderDate')),
                ('RequiredDeliveryDate', models.DateField(db_column='RequiredDeliveryDate')),
                ('SupplierName', models.CharField(db_column='SupplierName', max_length=80)),
            ],
            options={
                'db_table': 'PurchaseOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('RequestNumber', models.IntegerField(db_column='RequestNumber', primary_key=True, serialize=False)),
                ('RequestDate', models.DateField(db_column='RequestDate')),
            ],
            options={
                'db_table': 'ListaRequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestMedCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmountRequested', models.IntegerField(db_column='AmountRequested')),
            ],
            options={
                'db_table': 'RequestMedCode',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.DeleteModel(
            name='RequestArticulos',
        ),
        migrations.DeleteModel(
            name='Requisiciones',
        ),
    ]
