# Generated by Django 3.0.3 on 2020-04-12 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0005_auto_20200412_0144'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='Request',
        ),
    ]
