# Generated by Django 3.0.3 on 2020-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0006_auto_20200412_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='PReqMedCode',
            fields=[
                ('RequestNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MedCode', models.IntegerField()),
                ('AmountRequested', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PReqMedDesCode',
            fields=[
                ('RequestNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MedDescription', models.CharField(max_length=100)),
                ('AmountRequested', models.IntegerField()),
            ],
        ),
    ]
