# Generated by Django 3.0.3 on 2020-04-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0007_preqmedcode_preqmeddescode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsumption',
            fields=[
                ('ConsumptionNumber', models.IntegerField(db_column='ConsumptionNumber', primary_key=True, serialize=False)),
                ('ConsumptionDate', models.DateField(db_column='ConsumptionDate')),
                ('Department', models.CharField(db_column='Department', max_length=80)),
            ],
            options={
                'db_table': 'Patientconsumption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatConsMedCode',
            fields=[
                ('ConsumptionNumber', models.OneToOneField(db_column='ConsumptionNumber', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Inventarios.PatientConsumption')),
                ('AmountRequested', models.IntegerField(db_column='AmountRequested')),
            ],
            options={
                'db_table': 'PatConsMedCode',
                'managed': False,
            },
        ),
    ]
