# Generated by Django 3.0.3 on 2020-04-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0008_patconsmedcode_patientconsumption'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientconsumption',
            table='PatientConsumption',
        ),
    ]
