# Generated by Django 3.0.3 on 2020-04-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0009_auto_20200417_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='POinReq',
            fields=[
                ('PurchaseNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
