# Generated by Django 3.0.3 on 2020-04-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0010_poinreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poinreq',
            old_name='Quantity',
            new_name='count',
        ),
    ]
