# Generated by Django 3.0.3 on 2020-04-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0011_auto_20200417_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poinreq',
            old_name='count',
            new_name='Cantidad',
        ),
    ]
