# Generated by Django 3.0.3 on 2020-04-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0012_auto_20200417_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCReq',
            fields=[
                ('MedCode', models.IntegerField(primary_key=True, serialize=False)),
                ('MedDescription', models.CharField(max_length=100)),
                ('RequestNumber', models.IntegerField()),
                ('RequestDate', models.DateField()),
                ('AmountRequested', models.IntegerField()),
            ],
        ),
    ]
