# Generated by Django 3.0.3 on 2020-04-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventarios', '0013_mcreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='POinReq2',
            fields=[
                ('PurchaseNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MedDescription', models.CharField(max_length=100)),
                ('AmountPurchased', models.IntegerField()),
            ],
        ),
    ]
